version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=ort
      - MARIADB_DATABASE=ort_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:4.3
    ports:
      - '8080:8080' # HTTP
      - '8443:8443' # HTTPS
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=ort
      - MOODLE_DATABASE_NAME=ort_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME=user
      - MOODLE_PASSWORD=bitnami
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
